/*
 * This source file was generated by the Gradle 'init' task
 */
package snake;

import javax.swing.*;
import snake.model.GameModel;
import snake.view.GameView;
import snake.controller.GameController;

public class App {
    public static void main(String[] args) {
        GameModel model = new GameModel(30, 20);
        GameView view = new GameView(model);
        GameController controller = new GameController(model);

        JFrame frame = new JFrame("Snake Game");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.add(view);
        frame.pack();
        frame.setResizable(false);
        frame.setVisible(true);
        frame.addKeyListener(controller);

        Timer timer = new Timer(150, e -> {
            model.update();
        });
        timer.start();
    }
}
